sudo: required

services:
  - docker

before_install:
  - export PR_URL=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR_URL | jq -r .head.ref`; fi)
  - export DOCKER_TAG=$(if [ -n "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo "$BRANCH"; fi)
  - export DOCKER_IMAGE_NAME=wattpad/nodejs:$DOCKER_TAG
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - docker build -t $DOCKER_IMAGE_NAME .
  - docker push $DOCKER_IMAGE_NAME
